### ISSUE TITLE
Projectsの設定を適切に変更したい

### ISSUE THREAD

**Issue by Elise3993** [CASru-GAME/TeamGameDevBootcamp#11]
### 概要
- どうもProjectsの設定がうまくいっておらず、使いにくい気がするので変更したい

### 詳細
- 追加したIssueが自動でTodoに移動するようにする
- Issueがclosedになったら自動でdoneに移動するようにする
- Issueに紐づいたブランチからPRが出た時、Reviewに移動するようにする

(当projectsのurl)[https://github.com/users/Elise3993/projects/4/workflows]

**Comment by dugite-git** [comment]
[Actions を使用した Projects の自動化](https://docs.github.com/ja/issues/planning-and-tracking-with-projects/automating-your-project/automating-projects-using-actions)

[GitHub App の登録](https://docs.github.com/ja/apps/creating-github-apps/registering-a-github-app/registering-a-github-app)

以上の二つを行おうと思います。
