### ISSUE TITLE
.unity ファイルなどなども PRのFiles Changedの欄で Load Diff で隠されるようにする

### ISSUE THREAD

**Issue by AiletS** [CASru-GAME/TeamGameDevBootcamp#29]
.metaファイルのように.unityファイルにも適用したいです。冗長で長すぎて邪魔です。

**Comment by Elise3993** [comment]
↑補足
こういうやつです
![image](https://github.com/user-attachments/assets/0831565c-6580-48b8-9147-60fe4f6beae9)

**Comment by dugite-git** [comment]
https://support.atlassian.com/ja/bitbucket-cloud/docs/exclude-files-from-pull-request-diffs/
これ見たらできそう

**Comment by dugite-git** [comment]
どうやら基本的な設定としては設定できないっぽくて、PRのページに飛んだら毎回除外ファイル設定する必要あるみたい。

**Comment by AiletS** [comment]
そんな....理解しました。
