### ISSUE TITLE
Hp,Mp,Ap,Dpクラスの名前の再定義

### ISSUE THREAD

**Issue by AiletS** [CASru-GAME/TeamGameDevBootcamp#33]
今のうちにやっておくのが良さそう
Hp,Mp,Ap,Dpの名前にいったんしといたんですが、これ短すぎるしだめですね
クラス名を
- HealthPoint
- MagicPoint
- AttackPoint
- DefensePoint

とかに変えた方が良さそうです

**Comment by AiletS** [comment]
[クラスの設計図](https://github.com/CASru-GAME/TeamGameDevBootcamp/wiki/%E3%82%AF%E3%83%A9%E3%82%B9%E3%81%AE%E8%A8%AD%E8%A8%88%E5%9B%B3)

ここの修正予定に一応案を書いときました

**Comment by Elise3993** [comment]
> クラス名を
HealthPoint
MagicPoint
AttackPoint
DefensePoint
とかに変えた方が良さそうです

> 変数名も
CurrentValue
MaxValue
にするというアイデアが出ました

個人的に両方賛成です。

**Comment by AiletS** [comment]
クラス名と変数名を修正したバージョンを[クラスの設計図](https://github.com/CASru-GAME/TeamGameDevBootcamp/wiki/%E3%82%AF%E3%83%A9%E3%82%B9%E3%81%AE%E8%A8%AD%E8%A8%88%E5%9B%B3)
に上げときました(ExperiencePointクラスも追加しました)
確認お願いします

**Comment by Elise3993** [comment]
@AiletS 
確認したのですが、ExperiencePointに現在値と最大値があるのってどういう運用を想定してます？

**Comment by AiletS** [comment]
レベルアップには最大expまで到達する必要があるっていう想定で２つ用意しました
