### ISSUE TITLE
「_」に関する命名規則の提案

### ISSUE THREAD

**Issue by AiletS** [CASru-GAME/TeamGameDevBootcamp#35]
Hpクラスとか見ると
- _maxHp
- MaxHp
こう分かれているんですけどこれを
- _MaxHp
- MaxHp
にするように変えませんか？「_」が付いていて区分できるのに２文字も違くなるのが個人的に気にいらないんですが

皆さんはどうでしょうか

**Comment by Elise3993** [comment]
まだ本格的にコーディングしてないので実際に使ったときの使用感はわかりませんが、どうやらMicrosoftが公式に発表している命名方法らしいですし慣れたほうがいいような気がします

[private なフィールドにはアンダースコアを付ける (変更、設定)](https://qiita.com/Ted-HM/items/1d4ecdc2a252fe745871#private-%E3%81%AA%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%89%E3%81%AB%E3%81%AF%E3%82%A2%E3%83%B3%E3%83%80%E3%83%BC%E3%82%B9%E3%82%B3%E3%82%A2%E3%82%92%E4%BB%98%E3%81%91%E3%82%8B-%E5%A4%89%E6%9B%B4%E8%A8%AD%E5%AE%9A)

クラス内で使う方が`_maxHp`、外で使う方が`MaxHp`で同時に使う場面も無さそうですし

**Comment by AiletS** [comment]
はい
こう感じたのは私だけですので自分が慣れることにします
