### ISSUE TITLE
リポジトリの設定で、ブランチ・マージ関連の設定を適切に設定する

### ISSUE THREAD

**Issue by Elise3993** [CASru-GAME/TeamGameDevBootcamp#9]
ただ、具体的な設定項目は全く考えてないのでコメントで案が欲しいです（他人任せ）

**Comment by dugite-git** [comment]
設定した仕様
- PRした時にアプルーブが三つでマージできるようにする。
- スカッシュマージしかできないようにする。
- Require approval of the most recent reviewable push

**Comment by dugite-git** [comment]
以上で一旦設定を完了とします。
